name: Deploy to Mydevil

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  ftp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: SCP
      run: ftp -in -u ftp://${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}/ftptest/ *
